import { useState } from "react";
import type { SnapshotSessionSummary } from "../types/videoSnapshots";

export default function SnapshotSessionsHome({ sessions, currentId, lastId, busy, loading, onOpen, onNew, onImport, onRename, onDuplicate, onDelete, onRestore, onRefresh }: {
  sessions: SnapshotSessionSummary[]; currentId?: string; lastId: string; busy: boolean; loading: boolean;
  onOpen(id: string): void; onNew(): void; onImport(): void; onRename(entry: SnapshotSessionSummary): void;
  onDuplicate(entry: SnapshotSessionSummary): void; onDelete(entry: SnapshotSessionSummary): void;
  onRestore(entry: SnapshotSessionSummary): void; onRefresh(): void;
}) {
  const [search, setSearch] = useState("");
  const [deleted, setDeleted] = useState(false);
  const recent = sessions.filter(s => !s.deletedAt);
  const last = recent.find(s => s.id === (currentId || lastId)) || recent[0];
  const shown = sessions.filter(s => !!s.deletedAt === deleted && s.name.toLocaleLowerCase().includes(search.toLocaleLowerCase())).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt));
  return <section className="snapshots-sessions-home" aria-label="Snapshot sessions">
    <div className="snapshots-session-hero"><div><span className="snapshots-eyebrow">YOUR MOMENTS, READY WHEN YOU ARE</span><h2>Pick up where you left off.</h2><p>Original videos, selected frames and finishing touches—saved automatically on this computer.</p></div><div className="snapshots-session-hero-actions"><button className="snapshots-primary" onClick={onNew} disabled={busy || loading}>＋ New session</button>{last && <button aria-label={currentId === last.id ? "Return to session" : "Continue last session"} onClick={() => onOpen(last.id)} disabled={busy || loading}>{currentId === last.id ? "Return to session" : "Continue last session"}<small>{last.name}</small></button>}</div></div>
    <div className="snapshots-session-toolbar"><div role="group" aria-label="Session library view"><button aria-pressed={!deleted} onClick={() => setDeleted(false)}>Recent sessions <span>{recent.length}</span></button><button aria-pressed={deleted} onClick={() => setDeleted(true)}>Recently deleted <span>{sessions.length - recent.length}</span></button></div><input type="search" aria-label="Search sessions" placeholder="Search your sessions…" value={search} onChange={e => setSearch(e.target.value)}/><button onClick={onImport} disabled={busy || loading}>Import saved session</button><button onClick={onRefresh} disabled={busy || loading} aria-label="Refresh session library">↻</button></div>
    {loading ? <p role="status" className="snapshots-session-empty">Opening your session library…</p> : !shown.length ? <div className="snapshots-session-empty"><span>◇</span><h3>{search ? "No matching sessions" : deleted ? "Nothing in Recently deleted" : "Start with a moment worth keeping"}</h3><p>{search ? "Try another name." : deleted ? "Deleted sessions can be restored here. Your videos and exported photos are never deleted." : "Create a session, add your original videos and collect your favourite frames."}</p></div> : <div className="snapshots-session-grid">{shown.map(entry => <article className="snapshots-session-card" key={entry.id} aria-label={`Session ${entry.name}`}><div className="snapshots-session-card-top"><span className="snapshots-session-icon" aria-hidden="true">▣</span><span>{entry.id === currentId ? "CURRENT SESSION" : entry.deletedAt ? "RECOVERABLE" : "SAVED LOCALLY"}</span></div><h3>{entry.name}</h3><p>{entry.sourceCount} video{entry.sourceCount === 1 ? "" : "s"} · {entry.photoCount} selected photo{entry.photoCount === 1 ? "" : "s"}</p><time dateTime={entry.updatedAt}>Saved {new Date(entry.updatedAt).toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" })}</time>{entry.recovered && <p className="snapshots-warning">Recovered from the last-good save.</p>}<div className="snapshots-session-card-actions">{entry.deletedAt ? <button className="snapshots-primary" onClick={() => onRestore(entry)} disabled={busy}>Restore session</button> : <><button className="snapshots-primary" onClick={() => onOpen(entry.id)} disabled={busy}>{entry.id === currentId ? "Continue" : "Open"}</button><button onClick={() => onRename(entry)} disabled={busy}>Rename</button><button onClick={() => onDuplicate(entry)} disabled={busy}>Duplicate</button><button className="snapshots-session-delete" onClick={() => onDelete(entry)} disabled={busy} aria-label={`Delete session ${entry.name}`}>Delete</button></>}</div></article>)}</div>}
    <p className="snapshots-session-footnote">Sessions keep references to your videos, not copies. Keep the originals available. Export a session copy to move your work to another computer.</p>
  </section>;
}
